name: KMeans Workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Python and Node.js Dependencies
      run: |
        pip install -r requirements.txt
        npm install --prefix static

    - name: Run Application
      run: |
        make run &
        sleep 10
        # Check if server is running
        curl -f http://localhost:5000 || exit 1
